#pragma once

enum Flags : DATASIZE
{
	STATUS_Overflow = 1ui16,
	STATUS_Zero = 2ui16,
	STATUS_Negative = 4ui16,
	STATUS_Carry = 8ui16,
	STATUS_Truncated = 16ui16,

	ALU_DEREF_ADD,
	ALU_DEREF_SUB,
	ALU_DEREF_MUL,
	ALU_DEREF_DIV,
	ALU_DEREF_SHL,
	ALU_DEREF_SHR,

	ALU_NORM_ADD,
	ALU_NORM_SUB,
	ALU_NORM_MUL,
	ALU_NORM_DIV,
	ALU_NORM_SHL,
	ALU_NORM_SHR,

	ALU_REGISTER_ADD,
	ALU_REGISTER_SUB,
	ALU_REGISTER_MUL,
	ALU_REGISTER_DIV,
	ALU_REGISTER_SHL,
	ALU_REGISTER_SHR,

	ALU_POKE,
	ALU_BEGIN,
	ALU_BIND,

	MEMORY_PEEK,
	MEMORY_POKE,
	MEMORY_COPY,

	REGISTER_POKE,
	REGISTER_COPY,
	REGISTER_LOAD,
	REGISTER_SAVE,

	JUMP_UNCONDITIONAL,
	JUMP_EQUAL_ZERO,
	JUMP_NOT_EQUAL_ZERO
};